### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by chsuong** [CogComp/zoe#33]
I'm having difficulties installing the software, due to Java issues. What version of Java would you recommend installing to use your software? My CPU's OS is OSX (High Sierra).

Below is the output I get:
`(venv) (base) MacBook-Pro:zoe-master usr$ python3 scripts.py CHECKFILES
Traceback (most recent call last):
  File "scripts.py", line 6, in <module>
    from ccg_nlpy import local_pipeline
  File "/Users/usr/zoe-master/venv/lib/python3.6/site-packages/ccg_nlpy/local_pipeline.py", line 31, in <module>
    from jnius import autoclass
  File "/Users/usr/zoe-master/venv/lib/python3.6/site-packages/jnius/__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "/Users/usr/zoe-master/venv/lib/python3.6/site-packages/jnius/reflect.py", line 15, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/Users/usr/zoe-master/venv/lib/python3.6/site-packages/six.py", line 827, in __new__
    return meta(name, bases, d)
  File "jnius/jnius_export_class.pxi", line 114, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 164, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 45, in jnius.create_jnienv
  File "/Users/usr/zoe-master/venv/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'JAVA_HOME'`

So I set $JAVA_HOME to point to Java 8:
`(venv) (base) MacBook-Pro:zoe-master usr$ export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
(venv) (base) MacBook-Pro:zoe-master usr$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home`

Yet I still get an error:
`(venv) (base) MacBook-Pro:zoe-master usr$ python3 scripts.py CHECKFILES
Traceback (most recent call last):
  File "scripts.py", line 6, in <module>
    from ccg_nlpy import local_pipeline
  File "/Users/usr/zoe-master/venv/lib/python3.6/site-packages/ccg_nlpy/local_pipeline.py", line 31, in <module>
    from jnius import autoclass
  File "/Users/usr/zoe-master/venv/lib/python3.6/site-packages/jnius/__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "/Users/usr/zoe-master/venv/lib/python3.6/site-packages/jnius/reflect.py", line 15, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/Users/usr/zoe-master/venv/lib/python3.6/site-packages/six.py", line 827, in __new__
    return meta(name, bases, d)
  File "jnius/jnius_export_class.pxi", line 114, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 164, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
SystemError: Error calling dlopen(b'/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/lib/server/libjvm.dylib': b'dlopen(/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/lib/server/libjvm.dylib, 10): image not found'`

**Comment by Slash0BZ** [comment]
The only Java dependency is the cogcomp pipeline package https://github.com/CogComp/cogcomp-nlpy. It's a python client that calls local Java instances. I believe it uses JDK8 by default, and I can't say I have seen similar errors. 

In fact, you don't need the cogcomp-nlpy package. I used it mainly for tokenization. To just use ZOE, you can find all occurrences of `ccg_nlpy` in the code and remove them.  For example, in `scripts.py`, you can comment out line 6, which is where loading the Java dependencies. Let me know if that works for you.

**Comment by chsuong** [comment]
It worked. Thanks!
